#!/bin/bash
# Post-Harvest Field Validation System - Startup Guide
# Run this to start the complete system

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║           POST-HARVEST ANALYSIS WITH FIELD VALIDATION                     ║"
echo "║                      STARTUP WIZARD                                        ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

# Display Prerequisites
echo "📋 PREREQUISITES CHECK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Required:"
echo "  ✓ Python 3.8+"
echo "  ✓ Node.js & npm"
echo "  ✓ GEMINI_API_KEY environment variable"
echo ""
echo "Recommended:"
echo "  ✓ Visual Studio Code"
echo "  ✓ 2GB+ RAM"
echo "  ✓ Stable internet connection"
echo ""

# Display environment setup
echo "🔧 ENVIRONMENT SETUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Create .env file in backend_fastapi/:"
echo "   Location: backend_fastapi/.env"
echo "   Content:"
echo "   ┌────────────────────────────────┐"
echo "   │ GEMINI_API_KEY=your_key_here   │"
echo "   └────────────────────────────────┘"
echo ""

# Display startup steps
echo "🚀 STARTUP STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 1: Start Backend API Server"
echo "────────────────────────────────────"
echo "  cd backend_fastapi"
echo "  pip install -r requirements.txt  # if needed"
echo "  python main.py"
echo ""
echo "  Expected output:"
echo "  ✓ Uvicorn running on http://0.0.0.0:8000"
echo "  ✓ MongoDB connected (optional)"
echo ""

echo "STEP 2: Start Frontend (in new terminal)"
echo "─────────────────────────────────────────"
echo "  cd frontend"
echo "  npm install  # if needed"
echo "  npm run dev"
echo ""
echo "  Expected output:"
echo "  ✓ Vite dev server running"
echo "  ✓ Opens in browser at http://localhost:5173"
echo ""

echo "STEP 3: Test the System"
echo "───────────────────────"
echo "  Option A - Manual Testing:"
echo "    1. Open Post-Harvest Dashboard"
echo "    2. Select crop (e.g., Rice)"
echo "    3. Upload agricultural field image"
echo "    4. Observe validation result"
echo ""
echo "  Option B - Automated Testing (in new terminal):"
echo "    cd backend_fastapi"
echo "    python test_post_harvest_validation.py"
echo ""

echo "EXAMPLE WORKFLOW"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "User uploads farm image"
echo "         ↓"
echo "System validates it's agricultural (✅ 95% confidence)"
echo "         ↓"
echo "System verifies crop type matches (✅ Rice detected)"
echo "         ↓"
echo "Proceeds to full analysis:"
echo "  ✓ Harvest readiness: READY"
echo "  ✓ Quality grade: Grade A"
echo "  ✓ Damage: None"
echo "  ✓ Spoilage: No"
echo "  ✓ Phase: Harvesting ready"
echo "         ↓"
echo "Display recommendations to user"
echo ""

echo "WHAT YOU GET"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ NEW: Agricultural Field Validation"
echo "   └─ Uses Gemini Vision AI"
echo "   └─ Detects field type"
echo "   └─ Identifies crops"
echo "   └─ Shows confidence scores"
echo ""
echo "✨ NEW: Validation Error Messages"
echo "   └─ Clear explanation of errors"
echo "   └─ What was actually detected"
echo "   └─ Actionable recommendations"
echo ""
echo "✨ ENHANCED: Image Analysis"
echo "   └─ All endpoints auto-validate"
echo "   └─ Includes validation metadata"
echo "   └─ Confidence levels in responses"
echo ""
echo "✨ IMPROVED: User Experience"
echo "   └─ Non-agricultural images blocked"
echo "   └─ Crop mismatch detected"
echo "   └─ Clear error handling"
echo ""

echo "API ENDPOINTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Validation:"
echo "  POST /api/post-harvest/validate-field"
echo ""
echo "Image Analysis (with auto-validation):"
echo "  POST /api/post-harvest/check-readiness"
echo "  POST /api/post-harvest/grade-quality"
echo "  POST /api/post-harvest/detect-damage"
echo "  POST /api/post-harvest/detect-spoilage"
echo "  POST /api/post-harvest/detect-phase"
echo ""
echo "Text Recommendations:"
echo "  GET /api/post-harvest/harvesting-guidance"
echo "  GET /api/post-harvest/cleaning-sorting"
echo "  GET /api/post-harvest/drying-curing"
echo "  GET /api/post-harvest/storage-specs"
echo "  GET /api/post-harvest/packaging-guidance"
echo "  GET /api/post-harvest/transport-guidance"
echo "  GET /api/post-harvest/shelf-life"
echo "  GET /api/post-harvest/market-decision"
echo ""

echo "DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 Quick Start: QUICK_START.md"
echo "   └─ Step-by-step getting started guide"
echo ""
echo "📖 Technical Guide: POST_HARVEST_VALIDATION_GUIDE.md"
echo "   └─ Architecture, flow, responses, troubleshooting"
echo ""
echo "📖 Examples: FIELD_VALIDATION_SCENARIOS.md"
echo "   └─ 6 real-world scenarios with full request/response"
echo ""
echo "📖 Summary: IMPLEMENTATION_SUMMARY.md"
echo "   └─ Overview of all changes and improvements"
echo ""
echo "📖 Reference: REFERENCE_CARD.md"
echo "   └─ Quick reference with diagrams and checklists"
echo ""
echo "📖 Checklist: FINAL_CHECKLIST.md"
echo "   └─ Complete implementation verification"
echo ""

echo "TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Issue: API connection error"
echo "Fix: Make sure backend is running (python main.py)"
echo ""
echo "Issue: API key error"
echo "Fix: Check .env file has GEMINI_API_KEY set correctly"
echo ""
echo "Issue: Validation always fails"
echo "Fix: Try clearer image of agricultural field with good lighting"
echo ""
echo "Issue: Slow validation"
echo "Fix: Check internet connection and API quota"
echo ""

echo "NEXT STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. ✓ Set up .env with GEMINI_API_KEY"
echo "2. ✓ Start backend: cd backend_fastapi && python main.py"
echo "3. ✓ Start frontend: cd frontend && npm run dev"
echo "4. ✓ Test with agricultural field image"
echo "5. ✓ Read documentation for more details"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "                     ✅ READY TO START!"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Follow the steps above to start the Post-Harvest Analysis Dashboard"
echo "with agricultural field validation!"
echo ""
